name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:11
        env:
          POSTGRES_PASSWORD: postgres
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    steps:
    - name: Set up PostgreSQL 11
      run: |
        sudo apt-get -y install wget
        wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
        RELEASE=$(lsb_release -cs)
        echo "deb http://apt.postgresql.org/pub/repos/apt/ ${RELEASE}"-pgdg main | sudo tee  /etc/apt/sources.list.d/pgdg.list
        sudo apt-get update
        sudo apt-get -y install libpq-dev postgresql-client-11
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Ruby 2.7.0
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.0
    - name: Build and test
      env:
        PGHOST: localhost
        PGUSER: postgres
        PGPASSWORD: postgres
        RAILS_ENV: test
      run: |
        gem install bundler:2.1.2
        bundle config path vendor/bundle
        bundle install --jobs 4 --retry 3
        RAILS_ENV=test bundle exec rake db:drop
        RAILS_ENV=test bundle exec rake db:create
        RAILS_ENV=test bundle exec rake db:migrate
        bundle exec rspec
    - name: Login to Heroku Container registry
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:login
    - name: Build and push
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:push -a ${{ secrets.HEROKU_APP_NAME }} web
    - name: Release
      env:
        HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
      run: heroku container:release -a ${{ secrets.HEROKU_APP_NAME }} web
